name: Flutter App  Release

on:
  push:
    branches: 
    - master

jobs:
  build:
    name: Build APK and Create release
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '12.x'
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.0'
    
    - name: Decoding android/key.properties
    - run: echo "${{ secrets.KEY_PROPERTIES }}" | base64 --decode > android/key.properties

    - name: Decoding android/neumodore_key.jks
    - run: echo "${{ secrets.KEY_JKS }}" | base64 --decode > android/key.jks

    - run: flutter pub get
    
    # - run: flutter test
    
    - run: flutter build apk --release --split-per-abi
    
    - run: flutter build appbundle --release
    
    - name: Create Github Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/*.aab"
        token: ${{ secrets.RELEASES_TOKEN }}